port: 2355
save_video: true
seed: 0

PipelineParams:
  convert_SHs_python: False  # 是否直接使用 RGB
ModelParams:
  workspace: relay  # 模型名称
  sh_degree: 1
  bg_aug_ratio: 0.7  # 背景增强比例

GuidanceParams:
  model_key: 'stabilityai/stable-diffusion-2-1-base'
  text: 'a detailed macro photo of a relay with metallic contacts and a transparent casing.'
  negative: 'blurry, unrealistic, noisy, low-quality, plastic-like, unsharp, overexposed.'
  inverse_text: ''
  perpneg: false
  C_batch_size: 4
  t_range: [0.02, 0.5]
  max_t_range: 0.95
  lambda_guidance: 0.1
  guidance_scale: 8.0
  denoise_guidance_scale: 1.0
  noise_seed: 42

  ddim_inv: true
  annealing_intervals: true

  xs_delta_t: 180
  xs_inv_steps: 6
  xs_eta: 0.0
  
  delta_t: 90
  delta_t_start: 150

GenerateCamParams:
  init_shape: 'pointe'
  init_prompt: 'a relay.'  
  use_pointe_rgb: false
  init_num_pts: 120_000
  phi_range: [-180, 180]
  max_phi_range: [-180, 180]
  rand_cam_gamma: 1.1

  theta_range: [30, 90]
  max_theta_range: [30, 90]

  radius_range: [4.0, 4.5]
  max_radius_range: [3.5, 5.0]
  default_radius: 4.2
 
  default_fovy: 0.45
  fovy_range: [0.30, 0.55]
  max_fovy_range: [0.20, 0.55]

OptimizationParams:
  iterations: 5000
  save_process: True
  pro_frames_num: 500
  pro_render_45: False
  warmup_iter: 2000

  as_latent_ratio: 0.25
  geo_iter: 0
  densify_from_iter: 150
  densify_until_iter: 3500
  percent_dense: 0.005
  densify_grad_threshold: 0.00065
  progressive_view_iter: 800
  opacity_reset_interval: 400

  scale_up_cameras_iter: 600
  fovy_scale_up_factor: [0.8, 1.2]
  phi_scale_up_factor: 1.6