[general]
enable_bucket = true                        # 是否使用Aspect Ratio Bucketing

[[datasets]]
resolution = 512                            # 训练分辨率
batch_size = 1                              # 批次大小

  [[datasets.subsets]]
  image_dir = '/home/s414e2/CJH/LucidDreamer-main/lora_train_img/'                     # 指定包含训练图像的文件夹
  class_tokens = 'six bolt'                # 指定标识符类
  num_repeats = 20                          # 训练图像的重复次数
